//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseMethod.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutorsBooks
    {
        public int id { get; set; }
        public int AuthorID { get; set; }
        public int BooksID { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Books Books { get; set; }
    }
}
